exports.intents = ['weather', 'temperature', 'rain'];

exports.states = {
	'alabama' : 'AL',
	'alaska' : 'AK',
	'arizona' : 'AZ',
	'arkansas' : 'AR',
	'california' : 'CA',
	'colorado' : 'CO',
	'connecticut': 'CT',
	'delaware' : 'DE',
	'florida' : 'FL',
	'georgia' : 'GA',
	'hawaii' : 'HI',
	'idaho' : 'ID',
	'illinois' : 'IL',
	'indiana' : 'IN',
	'iowa' : 'IA',
	'kansas' : 'KA',
	'kentucky' : 'KY',
	'louisiana' : 'LA',
	'maine' : 'ME',
	'maryland' : 'MD',
	'massachussets' : 'MA',
	'michigan' : 'MI',
	'minnesota' : 'MN',
	'mississippi' : 'MS',
	'missouri' : 'MO',
	'montana' : 'MT',
	'nebraska' : 'NE',
	'nevada' : 'NV',
	'new Hampshire' : 'NH',
	'new Jersey' : 'NJ',
	'new Mexico' : 'NM',
	'new York' : 'NY',
	'north Carolina' : 'NC',
	'north Dakota' : 'ND',
	'ohio' : 'OH',
	'oklahoma' : 'OK',
	'oregon' : 'OR',
	'pennsylvania' : 'PA',
	'rhode Island' : 'RI',
	'south Carolina' : 'SC',
	'south Dakota' : 'SD',
	'tennessee' : 'TN',
	'texas' : 'TX',
	'utah' : 'UT',
	'vermont' : 'VT',
	'virginia' : 'VA',
	'washington' : 'WA',
	'west Virginia' : 'WV',
	'wisconsin' : 'WI',
	'wyoming' : 'WY'
	};
