exports.intents = ['weather', 'temperature', 'rain'];

exports.states = {
	"alabama" : "AL",
	"alaska" : "AK",
	"arizona" : "AZ",
	"arkansas" : "AR",
	"california" : "CA",
	"colorado" : "CO",
	"connecticut": "CT",
	"delaware" : "DE",
	"florida" : "FL",
	"georgia" : "GA",
	"hawaii" : "HI",
	"idaho" : "ID",
	"illinois" : "IL",
	"indiana" : "IN",
	"iowa" : "IA",
	"kansas" : "KA",
	"kentucky" : "KY",
	"louisiana" : "LA",
	"maine" : "ME",
	"maryland" : 'MD',
	"massachussets" : "MA",
	"michigan" : "MI",
	"minnesota" : "MN",
	"mississippi" : "MS",
	"missouri" : "MO",
	"montana" : "MT",
	"nebraska" : "NE",
	"nevada" : "NV",
	"new hampshire" : "NH",
	"new jersey" : "NJ",
	"new mexico" : "NM",
	"new york" : "NY",
	"north carolina" : "NC",
	"northdakota" : "ND",
	"ohio" : "OH",
	"oklahoma" : "OK",
	"oregon" : "OR",
	"pennsylvania" : "PA",
	"rhode island" : "RI",
	"south carolina" : "SC",
	"south dakota" : "SD",
	"tennessee" : 'TN',
	"texas" : 'TX',
	"utah" : 'UT',
	"vermont" : 'VT',
	"virginia" : 'VA',
	"washington" : 'WA',
	"west virginia" : 'WV',
	"wisconsin" : 'WI',
	"wyoming" : 'WY'
	};

